### ISSUE TITLE
Option to set the Default layout without adding new input methods

### ISSUE THREAD

**Issue by werererer** [fcitx/fcitx5-configtool#40]
It would be great to have this option(see title) because using a certain keyboard layout of a certain language doesn't imply using it as an input method. 
In other words I am using a german keyboard (no dead keys) as the default layout and use an american keyboard with altgr so that I can write umlauts (äöü) on it but don't want to have the german keyboard as an input method.

**Comment by wengxt** [comment]
I'm not so sure what you're asking for and expected behavior

But you can make setup like this
<img width="651" alt="image" src="https://user-images.githubusercontent.com/259684/112418474-c4612680-8ce6-11eb-8580-493e42192405.png">

This is what you want?

It will gives you some warning, you can simply ignore them if you just want it this way.

**Comment by werererer** [comment]
Oh yeah I just didn't read properly mybad xd
