### ISSUE TITLE
Some glitches with the French translation

### ISSUE THREAD

**Issue by rzhao271** [fcitx/fcitx5-configtool#56]
Firstly, thanks for fcitx5 and the related packages!
I had to install fcitx5-gtk and reboot to start using it, but fcitx5-diagnose helped me figure that out.

I also found some potential issues with the French translation in the config tool:
1. "Enumerate Input Method Group Forward" hasn't been translated.
2. "Restaurer les amp;défauts" has extra characters "amp;" in the string. Maybe it should be `&amp;`?

![Screenshot showing the aforementioned translation glitches](https://user-images.githubusercontent.com/7199958/184517629-8ebf5634-5284-4340-9939-86f4216f7e7a.png)

**Comment by wengxt** [comment]
Thanks for reporting, should be fixed by next translation sync.

https://github.com/fcitx/fcitx5/commit/97dfcd5278c39e3929774798f4d1e6251d342c19
https://github.com/fcitx/fcitx5-configtool/commit/e3727c4caae6f5d2c14e75a7b7736ed09efa690a#diff-d1848d6db2f62716a0f94bf24a87d1814f97724600b0ef79ac13931380f789a2

Also, if you want to help, you may join the translation team on https://www.transifex.com/fcitx/
